export const LOGIN_ACTION = 'LOGIN_ACTION';
export const REGISTER_ACTION = 'REGISTER_ACTION'
export const SHOW_ALL_POST = 'SHOW_ALL_POST'
export const DELETE_A_BLOGPOST = 'DELETE_A_BLOGPOST'
export const DELETE_A_BLOGPOST_SUCCESS = 'DELETE_A_BLOGPOST_SUCCESS'
export const REFRESH_MESSAGE = 'REFRESH_MESSAGE'
export const LOGIN_ACTION_FAILED = 'LOGIN_ACTION_FAILED'
export const LOAD_BLOGPOST_ACTION = 'LOAD_BLOGPOST_ACTION'